// frontend/src/components/ui/icons.ts
import {
  Home,
  Building2,
  Users,
  UserPlus,
  Settings,
  LogOut,
  Menu,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  MoreVertical,
  Plus,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  RefreshCw,
  Search,
  Filter,
  Download,
  Upload,
  Save,
  Check,
  CheckCircle,
  XCircle,
  AlertTriangle,
  Info,
  CircleAlert,
  Sprout,
  Warehouse,
  ShoppingCart,
  Package,
  FileText,
  BarChart3,
  Calendar,
  Clock,
  MapPin,
  User,
  DollarSign,
  TrendingUp,
  TrendingDown,
  ArrowRight,
  ArrowLeft,
  Loader2,
} from 'lucide-react';

export const Icons = {
  Home,
  Building: Building2,
  Users,
  UserPlus,
  Settings,
  Logout: LogOut,
  Menu,
  Close: X,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  More: MoreVertical,
  MoreVertical,
  Add: Plus,
  Edit,
  Delete: Trash2,
  View: Eye,
  Hide: EyeOff,
  Refresh: RefreshCw,
  Search,
  Filter,
  Download,
  Upload,
  Save,
  Check,
  Success: CheckCircle,
  Error: XCircle,
  Warning: AlertTriangle,
  Info,
  Alert: CircleAlert,
  Crop: Sprout,
  Warehouse,
  Procurement: ShoppingCart,
  Inventory: Package,
  Report: FileText,
  Analytics: BarChart3,
  Calendar,
  Clock,
  Location: MapPin,
  User,
  Money: DollarSign,
  Growth: TrendingUp,
  Decline: TrendingDown,
  ArrowRight,
  ArrowLeft,
  Loader: Loader2,
  TrendingUp,
  TrendingDown,
  Eye,
  EyeOff,
  CheckCircle,
  XCircle,
  AlertTriangle,
} as const;

export type IconName = keyof typeof Icons;
export type IconComponent = React.ComponentType<React.SVGProps<SVGSVGElement>>;